[package]
name = "libtest"
version = "0.1.0"
edition = "2021"

[dependencies]
getopts = "0.2.21"

[target.'cfg(not(all(windows, target_env = "msvc")))'.dependencies]
libc = { version = "0.2.150", default-features = false }
